apiVersion: v1
kind: Service
metadata:
  name: cloud-notes-backend-service
  namespace: cloud-notes
spec:
  selector:
    app: cloud-notes-backend
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: ClusterIP
