server {
  listen 80;
  server_name _;
  server_tokens off;

  root /usr/share/nginx/html;
  index index.html;

  location = /health {
    proxy_pass http://backend:5000/health;
  }

  location = /identity {
    proxy_pass http://backend:5000/identity;
    proxy_set_header X-Amzn-Ava-User-Context $http_x_amzn_ava_user_context;
  }

  location /api/ {
    proxy_pass http://backend:5000;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
